#!/bin/bash

sudo apt-get update
sudo apt-get -y install nginx
systemctl is-active nginx
sudo systemctl start nginx

echo "Nginx script is running"
sleep 1

if(systemctl is active nginx):
then
  sudo mkdir /var/www/html/labs
  sudo chown $ronald:root /var/www/html/labs

  ln -s /var/www/html/labs html

  cd html
  touch index.html
  nano index.html

  <html>
      <body>
      <h1>STUDENT INFORNAMTION PAGE</h1>
      <p>R</p>
      <p>Student Name:Ronald</p>
      <p>Student No:221036660 </p>
      <p>Course:Computer Systems</p>
      </body>
  </html>

  else
  echo"error"
  exit 1

  fi
./websvr_config_script.bash


sudo apt update
sudo apt install mysql-server
sudo mysql_secure_installation
n
n
n
y
sudo passwd
sudo ufw allow 3306/tcp
sudo ufw reload
sudo mysql -u root -p 
enter password
CREATE DATABASE studentManagement;
USE studentManagement;
  CREATE TABLE students (
    student_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    age INT,
    gender VARCHAR(10),
    course VARCHAR(50)
  );
INSERT INTO studentInfo (id, name, age, gender, course) VALUES(123,'Ronald',21,'male','computer');
INSERT INTO studentInfo (id, name, age, gender, course) VALUES(124,'Ndlovu',23,'male','computer');
INSERT INTO studentInfo (id, name, age, gender, course) VALUES(125,'James',22,'male','engineering');
INSERT INTO studentInfo (id, name, age, gender, course) VALUES(126,'Mandy',21,'female','fashion');
INSERT INTO studentInfo (id, name, age, gender, course) VALUES(123,'Retha',20,'female','computer');
SELECT * FROM studentInfo;

Quit
Exit
