#!/bin/bash

sudo apt-get update
sudo apt-get -y install nginx
systemctl is-active nginx
sudo systemctl start nginx

echo "Nginx script is running"
sleep 1

if(systemctl is active nginx):
then
  sudo mkdir /var/www/html/labs
  sudo chown $ronald:root /var/www/html/labs

  ln -s /var/www/html/labs html

  cd html
  touch index.html
  nano index.html

  <html>
      <body>
      <h1>STUDENT INFORNAMTION PAGE</h1>
      <p>R</p>
      <p>Student Name:Ronald</p>
      <p>Student No:221036660 </p>
      <p>Course:Computer Systems</p>
      </body>
  </html>

  else
  echo"error"
  exit 1

  fi
